#!/usr/bin/env bash
# Automatically generated by Noctalia

export FZF_DEFAULT_OPTS="
--color=bg+:{{colors.surface_container.default.hex}}
--color=bg:{{colors.surface.default.hex}}
--color=spinner:{{colors.primary.default.hex}}
--color=hl:{{colors.primary.default.hex}}
--color=fg:{{colors.on_surface.default.hex}}
--color=header:{{colors.primary.default.hex}}
--color=info:{{colors.secondary.default.hex}}
--color=pointer:{{colors.primary.default.hex}}
--color=marker:{{colors.primary.default.hex}}
--color=fg+:{{colors.on_surface.default.hex}}
--color=prompt:{{colors.primary.default.hex}}
--color=hl+:{{colors.primary.default.hex}}
--color=border:{{colors.outline.default.hex}}
--height=40%
--border=rounded
--info=inline
--preview-window=right:50%:wrap
--bind='ctrl-u:preview-page-up,ctrl-d:preview-page-down'
--bind='ctrl-f:page-down,ctrl-b:page-up'
--bind='alt-a:select-all,alt-d:deselect-all'
--bind='ctrl-/:toggle-preview'
"

# FZF command configurations with theme colors
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'

# FZF preview commands with syntax highlighting
export FZF_CTRL_T_OPTS="
--preview 'bat --color=always --style=numbers --line-range=:500 {}'
--preview-window 'right:50%:wrap'
"

export FZF_ALT_C_OPTS="
--preview 'tree -C {} | head -200'
--preview-window 'right:50%:wrap'
"

# FZF completion trigger
export FZF_COMPLETION_TRIGGER='**'

# FZF completion options (colors inherited from FZF_DEFAULT_OPTS)
export FZF_COMPLETION_OPTS="
--border
--info=inline
"
