#!/usr/bin/env bash
set -euo pipefail

systemctl --user enable --now gammastep
systemctl --user enable --now gsettings
systemctl --user enable --now shikane
systemctl --user enable --now mako
systemctl --user enable --now polkit-agent
systemctl --user enable --now sway-bg
systemctl --user enable --now sway-idle
systemctl --user enable --now wob
systemctl --user enable --now waybar
