#!/bin/sh

systemctl --user enable --now mbsync.timer

# Custom
systemctl --user enable --now flashfocus
systemctl --user enable --now gammastep
systemctl --user enable --now gsettings
systemctl --user enable --now kanshi
systemctl --user enable --now libinput-gestures
systemctl --user enable --now mako
systemctl --user enable --now notification-sounds
systemctl --user enable --now polkit-gnome
systemctl --user enable --now sway-bg
systemctl --user enable --now sway-idle
systemctl --user enable --now wob
systemctl --user enable --now waybar
