#!/usr/bin/env bash
set -euo pipefail

dconf_dir=${XDG_CONFIG_HOME:-$HOME/.config}/dconf/

for file in "$dconf_dir"*.conf; do
  [ -f "$file" ] || continue
  base=$(basename "$file" .conf)
  dconf_path=$(printf '/%s/' "$base" | tr '.' '/')
  dconf load "$dconf_path" <"$file"
done
