#!/usr/bin/env bash
set -euo pipefail

DUMPS_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/dconf/

cd "$DUMPS_DIR" || exit

for file in *.conf; do
  DCONF_PATH=$(echo ".$file." | sed -e 's/\.conf//g' | sed -e 's/\./\//g')
  dconf load "$DCONF_PATH" <"$file"
done
