#!/usr/bin/env python3

import gi.repository.GLib
import dbus
import re
from dbus.mainloop.glib import DBusGMainLoop
import sounddevice as sd
import subprocess

def notifications(bus, message):
  keys = ["app_name", "replaces_id", "app_icon", "summary",
          "body", "actions", "hints", "expire_timeout"]
  args = message.get_args_list()

  if len(args) == 8:
    notification = dict([(keys[i], args[i]) for i in range(8)])

    if (notification["app_name"] == "Firefox"):
      if (re.match( r'\d\d:\d\d\s–\s\d\d:\d\d$', notification["body"], re.I)):
        p = subprocess.Popen('mpv /usr/lib/libreoffice/share/gallery/sounds/left.wav', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        retval = p.wait()

DBusGMainLoop(set_as_default=True)

bus = dbus.SessionBus()
bus.add_match_string_non_blocking("eavesdrop=true, interface='org.freedesktop.Notifications', member='Notify'")
bus.add_message_filter(notifications)

mainloop = gi.repository.GLib.MainLoop()
mainloop.run()
