#!/usr/bin/env bash

if $(hostname | grep -q corp); then
  swayidle -w \
    timeout 300 'swaylock' \
    before-sleep 'swaylock'
else
  swayidle -w \
    timeout 300 'swaylock' \
    timeout 600 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock'
fi
