#? Config file for btop v.1.4.6

color_theme = "noctalia"
presets = "cpu:1:braille,proc:0:braille cpu:0:braille,mem:0:braille,net:0:braille cpu:0:braille,mem:0:braille,net:0:braille,proc:0:braille"
vim_keys = true
graph_symbol_cpu = "braille"
graph_symbol_gpu = "braille"
graph_symbol_mem = "braille"
graph_symbol_net = "braille"
graph_symbol_proc = "braille"
proc_sorting = "cpu direct"
proc_tree = true
proc_per_core = true
net_auto = true
show_battery = true
show_battery_watts = true
show_cpu_watts = true
log_level = "WARNING"
save_config_on_exit = false
nvml_measure_pcie_speeds = true
rsmi_measure_pcie_speeds = true
