[/]
color-scheme='prefer-dark'
cursor-size=24
cursor-theme='Adwaita'
enable-animations=true
font-antialiasing='rgba'
font-hinting='slight'
font-name='Sans'
font-rgba-order='rgb'
gtk-theme='adw-gtk3-dark'
icon-theme='Papirus'
scaling-factor=uint32 1
text-scaling-factor=1.0
