#!/usr/bin/env bash
# Automatically generated by Noctalia

export FZF_DEFAULT_OPTS="
--color=bg+:#1c1c1c
--color=bg:#0c0c0c
--color=spinner:#ffc799
--color=hl:#ffc799
--color=fg:#ffffff
--color=header:#ffc799
--color=info:#99ffe4
--color=pointer:#ffc799
--color=marker:#ffc799
--color=fg+:#ffffff
--color=prompt:#ffc799
--color=hl+:#ffc799
--color=border:#5e5e5e
--height=40%
--border=rounded
--info=inline
--preview-window=right:50%:wrap
--bind='ctrl-u:preview-page-up,ctrl-d:preview-page-down'
--bind='ctrl-f:page-down,ctrl-b:page-up'
--bind='alt-a:select-all,alt-d:deselect-all'
--bind='ctrl-/:toggle-preview'
"

# FZF command configurations with theme colors
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'

# FZF preview commands with syntax highlighting
export FZF_CTRL_T_OPTS="
--preview 'bat --color=always --style=numbers --line-range=:500 {}'
--preview-window 'right:50%:wrap'
"

export FZF_ALT_C_OPTS="
--preview 'tree -C {} | head -200'
--preview-window 'right:50%:wrap'
"

# FZF completion trigger
export FZF_COMPLETION_TRIGGER='**'

# FZF completion options (colors inherited from FZF_DEFAULT_OPTS)
export FZF_COMPLETION_OPTS="
--border
--info=inline
"
