#!/usr/bin/env bash
# Automatically generated by Noctalia

export FZF_DEFAULT_OPTS="
--color=bg+:#29263c
--color=bg:#15141b
--color=spinner:#a277ff
--color=hl:#a277ff
--color=fg:#edecee
--color=header:#a277ff
--color=info:#61ffca
--color=pointer:#a277ff
--color=marker:#a277ff
--color=fg+:#edecee
--color=prompt:#a277ff
--color=hl+:#a277ff
--color=border:#6d6d6d
--height=40%
--border=rounded
--info=inline
--preview-window=right:50%:wrap
--bind='ctrl-u:preview-page-up,ctrl-d:preview-page-down'
--bind='ctrl-f:page-down,ctrl-b:page-up'
--bind='alt-a:select-all,alt-d:deselect-all'
--bind='ctrl-/:toggle-preview'
"

# FZF command configurations with theme colors
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'

# FZF preview commands with syntax highlighting
export FZF_CTRL_T_OPTS="
--preview 'bat --color=always --style=numbers --line-range=:500 {}'
--preview-window 'right:50%:wrap'
"

export FZF_ALT_C_OPTS="
--preview 'tree -C {} | head -200'
--preview-window 'right:50%:wrap'
"

# FZF completion trigger
export FZF_COMPLETION_TRIGGER='**'

# FZF completion options (colors inherited from FZF_DEFAULT_OPTS)
export FZF_COMPLETION_OPTS="
--border
--info=inline
"
