#!/usr/bin/env bash

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

alias ls="ls --color=auto"
alias l="ls -lFh --color=auto"
alias la="ls -laFh --color=auto"
alias lsd='ls -lF --color=auto | grep "^d"'

alias vgit="vcsh dotfiles"
alias fire="DISPLAY= cacafire"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias em="emacs"
alias emc="TERM=screen-256color emacsclient -t -a=vi"

alias k="kubectl"
alias vim="emc"

alias sway="exec systemd-cat --identifier=sway sway"
