#!/usr/bin/env bash

alias grep="grep --color=auto"
alias egrep="grep -E --color=auto"
alias fgrep="grep -F --color=auto"

alias ls="eza"
alias l="eza -lhF"
alias la="eza -lahF"
alias lsd="eza -lF --only-dirs"

alias vgit="vcsh dotfiles"
alias fire="DISPLAY= cacafire"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias em="emacs"
alias emc="TERM=screen-256color emacsclient -t -a=vi"

alias k="kubectl"
alias vim="emc"

alias sway="exec systemd-cat --identifier=sway sway"
