#!/usr/bin/env bash

for f in "$HOME"/.config/environment.d/*; do
    [[ -r "$f" ]] || continue
    while IFS= read -r l; do
        [[ "$l" =~ ^[[:space:]]*(#|$) ]] && continue
        eval export "$l"
    done < "$f"
done

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --height 40% --border"
