#!/usr/vin/env bash

FILES=~/.config/environment.d/*
for f in $FILES
do
  while read -r l; do
    eval export "$l"
  done < <(grep . "$f")
done

export SKIM_DEFAULT_OPTIONS="--color=16,fg:08,bg:,current:01,current_bg:,matched:03,matched_bg:,current_match:01,current_match_bg:,marker:04,spinner:04,prompt:04,info:04,header:04"
