#!/usr/bin/env bash

FILES=~/.config/environment.d/*
for f in $FILES; do
    while read -r l; do
        eval export "$l"
    done < <(grep . "$f")
done

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

_gen_fzf_default_opts() {
    export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS""\
 --height 40% --border"
}

_gen_fzf_default_opts
