--no-default-browser-check
--disable-default-apps
--disable-login-animations
--disable-modal-animations
--enable-zero-copy
--ozone-platform=wayland
--enable-features=WebUIDarkMode,NativeNotifications,WaylandWindowDecorations
--enable-wayland-ime
