--no-default-browser-check
--disable-default-apps
--disable-login-animations
--disable-modal-animations
--enable-zero-copy
--ozone-platform-hint=auto
--enable-features=WebUIDarkMode,NativeNotifications,WaylandWindowDecorations,Vulkan
--enable-wayland-ime
