#!/bin/bash

# Main network interface
export NETWORK_INTERFACE=$(ip link show | grep -oh "\w*wlp\w*")
CORE_TEMP_PATH=""

# Main proc temp
for i in /sys/class/hwmon/hwmon*/temp*_input; do
	SENSOR=$(echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)")
  IS_CORE_TEMP=$(echo $SENSOR  | grep -c "coretemp")

  if [ $IS_CORE_TEMP -ne 0 ]; then
      CORE_TEMP_PATH=$(echo $SENSOR | grep -oE '[^ ]+$')
      break
  fi
done

export CORE_TEMP_PATH

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch main bar
(sleep 3; polybar main) &
